on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          npx --yes @xriss/dilf format --json-to-xml --dirs json-to-xml >>generated.txt
          npx --yes @xriss/dilf format --json-to-md --dirs json-to-md >>generated.txt
          npx --yes @xriss/dilf format --xml-to-json --dirs xml-to-json >>generated.txt
          npx --yes @xriss/dilf format --xml-to-md --dirs xml-to-md >>generated.txt
          npx --yes @xriss/dilf format --md-to-json --dirs md-to-json >>generated.txt
          npx --yes @xriss/dilf format --md-to-xml --dirs md-to-xml >>generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
          
